# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  - group: ACR_Valiables
  - name: imageName
    value: myimage:$(Build.buildId)
  - name: acrId
    value: $(ACR_USERNAME)
  - name: acrPassword
    value: $(ACR_PASSWORD)
  - name: acrServer
    value: $(ACR_SERVER)

steps:
  - script: |
      docker build -t $(acrServer)/$(imageName) .
      docker login -u $(acrId) -p $(acrPassword) $(acrUrl)
      docker push $(acrServer)/$(imageName)

    displayName: Build Docker image